### ISSUE TITLE
use custom model?

### ISSUE THREAD

**Issue by dvschultz** [greentfrapp/lucent#16]
Hi, 
I see its possible to use models from the modelzoo, is it possible to use a custom trained model? Ay documentation or direction would be appreciated.

**Comment by humzaiqbal** [comment]
Yeah, you can. Notice in the [ModelZoo Colab Notebook](https://colab.research.google.com/github/greentfrapp/lucent-notebooks/blob/master/notebooks/modelzoo.ipynb#scrollTo=zYmw3PPBfiLs) they have the following code

```
from torchvision.models import resnet50

resnet50_model = resnet50(pretrained=True).to(device).eval()
_ = render.render_vis(resnet50_model, "layer4_1_conv1:121", show_inline=True)
```
You can treat out of the box models the exact same way as modelzoo ones

**Comment by MHong1001** [comment]
But I keep having the issue of 

> AssertionError: There are no saved feature maps. Make sure to put the model in eval mode, like so: `model.to(device).eval()`. See README for example.

even though I have already set the model in eval mode.

**Comment by MHong1001** [comment]
I am trying to visualize a model that receives 1 channel input, but it shows

> AssertionError: There are no saved feature maps. Make sure to put the model in eval mode, like so: `model.to(device).eval()`. See README for example.

It works fine if the model receives 3 channels input. How can I modified the code so that it can be used on a custom model that receives 1 channel input?

**Comment by greentfrapp** [comment]
I'll have an update over the weekend!

**Comment by MHong1001** [comment]
Greatly appreciate your efforts!

**Comment by greentfrapp** [comment]
Hi @MHong1001, thanks for your interest in Lucent!

If your model only receives 1 channel input, you will need to disable `preprocess` and explicitly set `transforms=[]` (or your desired transformations. You should also initialize your own `param_f` input with `channels=1`.

Here's a code snippet that should help. The `model` here is simply a conv layer that takes a 1 channel input.

```
model = torch.nn.Sequential(torch.nn.Conv2d(1, 10, (3, 3))).to(device).eval()
param_f = lambda: param.image(128, channels=1)
_ = render.render_vis(model, "0:0", param_f, transforms=[], preprocess=False, show_inline=True)
```

**Comment by miratshah27** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/88181752/222078731-5ce698b9-7f64-4616-a406-efdfcec1c9ea.png">
Please help out with this....

**Comment by HTalNachmani** [comment]
You certainly don't need the help anymore, but I'll leave this here in case that others get into the same problem. I was trying to run Lucent on a custom model, and I kept getting the same error "AssertionError: There are no saved feature maps". What solved it for me was to run an inference on the model once after initializing it and loading in the weights. After that Lucent worked normally! :) 

Like this: 
![image](https://github.com/greentfrapp/lucent/assets/115075932/6b99c033-1a3e-4921-b440-5d0354fabaab)
