### ISSUE TITLE
Q: Do you use the same architecture and weights as Clarity does?

### ISSUE THREAD

**Issue by gergopool** [greentfrapp/lucent#17]
Hi,

I am looking for a trainable InceptionV1 model which shares the same weights with the ones Clarity team uses.
Reading your code, I've found these lines:
```python
model_urls = {
    # InceptionV1 model used in Lucid examples, converted by ProGamerGov
    'inceptionv1': 'https://github.com/ProGamerGov/pytorch-old-tensorflow-models/raw/master/inception5h.pth',
}
```
Does it mean you're using exactly the same architecture and weights, so your render_vis function can reproduce the same pictures that Clarity has published?

Thanks!

**Comment by greentfrapp** [comment]
Yup that's true for the InceptionV1 model. The model weights provided by @ProGamerGov are the same ones used by the Clarity team in their [Lucid examples](https://github.com/tensorflow/lucid) and also [OpenAI Microscope](https://microscope.openai.com/models/inceptionv1).

**Comment by ProGamerGov** [comment]
@gergopool The team that created the InceptionV1 had some confusion with version naming and thus listed the model as inception5h in some places. To add to that confusion, InceptionV1 is also known as GoogleNet in some places.

**Comment by gergopool** [comment]
Thanks! I've just double-checked it on two neurons, the visualizations are nearly the same as the ones I got with the lucid repo.

Great work! :)
