### ISSUE TITLE
PyTorch 1.7 support

### ISSUE THREAD

**Issue by Tal-Golan** [greentfrapp/lucent#20]
Kornia 0.4.1. (available on PyPI) supports PyTorch 1.7. Is there a reason not to update the requirements so lucent supports PyTorch 1.7 as well? Is there some functionality expected to break?

**Comment by greentfrapp** [comment]
Thanks @Tal-Golan for raising this! I've released a version that's compatible with kornia 0.4.1 (there was a small breaking change but it's been fixed)
