### ISSUE TITLE
Activation Grid Notebook

### ISSUE THREAD

**Issue by greentfrapp** [greentfrapp/lucent#3]
Reproduce Lucid's Activation Grid [Notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/building-blocks/ActivationGrid.ipynb) with PyTorch and Lucent.

The only new function required seems to be [ChannelReducer](https://github.com/tensorflow/lucid/blob/master/lucid/misc/channel_reducer.py), which doesn't rely on Tensorflow so it should be relatively simple to port over.

Help wanted for this!

**Comment by mehdidc** [comment]
Hi @greentfrapp, thanks for doing this, I have been looking for/planning to do a PyTorch port of lucid for a while. If no one is already working on this, I will do it.

**Comment by greentfrapp** [comment]
Hey @mehdidc thanks for the interest! Help with this will be much appreciated!

**Comment by greentfrapp** [comment]
Closed by #4
