### ISSUE TITLE
get raw_activations

### ISSUE THREAD

**Issue by 2nayk** [greentfrapp/lucent#31]
Hi, thanks for this great library!
I'm trying to reproduce the [Activation Atlas notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/activation-atlas/activation-atlas-simple.ipynb) using lucent, creating grid cells in the end.

In the notebook, "raw activation" is available in a numpy.ndarray format by "model.layers[7].activations" to utilise in the next Dimensionality reduction section. How can I get this raw activation using lucent?

I did create visualised images using lucent render_vis first, and then flattened them to use UMAP fit method, but I'm not sure this is correct. 
Any suggestion would be appreciated.

**Comment by greentfrapp** [comment]
Hi @2nayk! Thanks so much for checking out `lucent`! The `activations`attribute seen in the Activation Atlas notebook is actually obtained by iterating over ImageNet samples (see the docstring in https://github.com/tensorflow/lucid/blob/master/lucid/modelzoo/aligned_activations.py). Unfortunately as of now, `lucent` has no support for this and I am busy at the moment so I probably won't have time to build this feature. But I'll be happy to merge any PRs that would help `lucent` support this!

**Comment by 2nayk** [comment]
Hello @greentfrapp. Thank you so much for looking into this and sending me the relevant link. For the time being, I will follow the lucid code for my dataset :)
